### ISSUE TITLE
Glitch in display of 'authentication' in Ontobee

### ISSUE THREAD

**Issue by alanruttenberg** [d-acts/d-acts#6] opened 2016-10-15 19:41 UTC
http://www.ontobee.org/ontology/d-acts?iri=http://purl.obolibrary.org/obo/IAO_0020023

It says:
(has part some information content entity) and (_:vb387732219 some identity document) and (has part only information content entity)

Usually this indicates something off in the RDF for the ontology.

**Comment by mbrochhausen** [comment] 2016-10-15 20:09
Thanks Alan. I looked at it and  it is intended to say "inverse 'is about' some identity document. I looked at the RDF and it seemed fine to me. Would you mind taking a look to:
"<rdf:Description>
                                        <owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000136"/>
                                    </rdf:Description>"

**Comment by mbrochhausen** [comment] 2016-10-15 20:12
wait the code does seem to show...
<owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000136">

**Comment by mbrochhausen** [comment] 2016-10-19 17:45
According to Edison Ong Ontobee does at this point not allow to represent inverse properties. He and Oliver He will start working on that in the near future. In this light, I am going to close this issue, since the problem is not with our code, but OntoBee.

**Closed by mbrochhausen** 2016-10-19 17:45 UTC
